server.servlet.context-path=/image-service
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:imagesdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
#spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none
useImages=true
server.port=8090
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.security.enabled=false
