server.servlet.context-path=/ecommerce-service
server.port=8090
management.endpoints.web.exposure.include=*
management.endpoint.health.probes.enabled=true
services.product.base-url=http://product-service:8090
services.images.base-url=http://images-service:8090
useImages=true
