apiVersion: apps/v1
kind: Deployment
metadata:
  name: images
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: images
  template:
    metadata:
      labels:
        app: images
    spec:
      containers:
        - name: images
          image: images:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090
          envFrom:
            - configMapRef:
                name: images-config
          readinessProbe:
            httpGet:
              path: /image-service/actuator/health/readiness
              port: 8090
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /image-service/actuator/health/liveness
              port: 8090
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
