apiVersion: v1
kind: Service
metadata:
  name: images-service
  namespace: ecommerce
spec:
  type: ClusterIP
  selector:
    app: images
  ports:
    - name: http
      port: 8090
      targetPort: 8090
