version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:8080"
  consul:
    command: -server -bootstrap -advertise ${HOST_IP}
    image: progrium/consul
    container_name: consul
    ports:
      - "8500:8500"
  product:
    image: product:latest
  images:
    image: images:latest
  ecommerce:
    image: ecommerce:latest
