apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  SERVER_PORT: "8090"
  SERVER_SERVLET_CONTEXT_PATH: "/ecommerce-service"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  SERVICES_PRODUCT_BASE_URL: "http://product-service:8090"
  SERVICES_IMAGES_BASE_URL: "http://images-service:8090"
  USE_IMAGES: "true"
