apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers:
        - name: ecommerce
          image: ecommerce:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090
          envFrom:
            - configMapRef:
                name: ecommerce-config
          readinessProbe:
            httpGet:
              path: /ecommerce-service/actuator/health/readiness
              port: 8090
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ecommerce-service/actuator/health/liveness
              port: 8090
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
